### ISSUE TITLE
Schema for openweather not found

### ISSUE THREAD

**Issue by Durlyn** [jenslody/gnome-shell-extension-openweather#102]
Hi!
in gnome 3.18 after installing the extension can not go into the settings.
Error: Schema org.gnome.shell.extensions.openweather could not be found for extension openweather-extension@jenslody.de. Please check your installation. 
what need to do to fix it?

**Comment by jenslody** [comment]
What is your installation source ?

**Comment by Durlyn** [comment]
from git. OS Fedora 23.

**Comment by shlinux** [comment]
Same problem.

**Comment by jenslody** [comment]
Do you have glib2 development packages installed, as mentioned in the installation section of the [wiki](https://github.com/jenslody/gnome-shell-extension-openweather/wiki/Installation) and the Readme ?

**Comment by Durlyn** [comment]
thanks. need install glib2-devel package. after installing all worked.
