### ISSUE TITLE
Can't add new locations

### ISSUE THREAD

**Issue by ptkato** [jenslody/gnome-shell-extension-openweather#104]
The OK button seems to be not enabled, event if a location (any) is picked:

![broken button](http://i.imgur.com/KhQ5Etw.png)

Debian Jessie, Gnome 3.14.1;

**Comment by jenslody** [comment]
Either bug the debian maintainers to update their package to a recent version, or remove it (it's xalled gnome-shell-extension-weather on Debian) and install the version from https://extensions.gnome.org/extension/750/openweather/ .
It's compatible with gnome-shell 3.8 and 3.10 again and works fine on Debian jessie.

**Comment by ptkato** [comment]
This one is what is installed. And the Tweak Tool doesn't allow me to remove extensions which came installed as default.

**Comment by jenslody** [comment]
You need to remove it with the package manager, should be "sudo apt remove gnome-shell-extension-weather" .
