### ISSUE TITLE
Can't press OK button to add new location

### ISSUE THREAD

**Issue by XenGi** [jenslody/gnome-shell-extension-openweather#111]
When I try to add a new location I type in `berlin` and a list cames. I select `Berlin, DE [2950159]` but the `OK` button is still disabled. Can't find a way to add the location.

What am I doing wrong?

**Comment by jenslody** [comment]
You use an outdated version of the extension.
Where did you get it from, which version of gnome-shell do you use ?

**Comment by XenGi** [comment]
I'm using gnome-shell 3.14.4-1~deb8u1 installed from debian jessie repos. The extension was preinstalled with gnome.
I try to use the one from extensions.gnome.org.

**Comment by jenslody** [comment]
A more recent version is in Debian testing, see the first comment (of valerietheblonde) on https://extensions.gnome.org/extension/750/openweather/ .
