### ISSUE TITLE
Forecast.io not working

### ISSUE THREAD

**Issue by robertmathew** [jenslody/gnome-shell-extension-openweather#113]
Using Ubuntu 15.10, Gnome 3.8.
I installed OpenWeather using this command `sudo apt-get install gnome-shell-extension-weather`

I am trying to use Forecast.io API key, but its isn't working.
This is my location weather `https://forecast.io/#/f/9.2648,76.7870`. Even I am getting the data from this API call `https://api.forecast.io/forecast/<API_KEY>/9.2648,76.7870`

![screenshot from 2016-01-25 13-40-25](https://cloud.githubusercontent.com/assets/2344947/12545579/8aae4c2a-c369-11e5-9573-69f8c7aec162.jpg)

I even tried a different location, still no weather data.

**Comment by jenslody** [comment]
Can you please check "/usr/share/gnome-shell/extensions/openweather-extension@jenslody.de/forecast_io.js" whether it uses "https" or "http" for OPENWEATHER_URL_BASE ?
It's plain http, please change it to https and reload the shell (and ask the ubuntu maintainers to update the extension).

**Comment by robertmathew** [comment]
Changing to https fixed the issue. Thanks.
