### ISSUE TITLE
issue with maximum and minimum temperatures

### ISSUE THREAD

**Issue by ousia** [jenslody/gnome-shell-extension-openweather#117]
@jenslody, I’m not sure data from OpenWeatherMap.org are imported right.

I attach a sample image:

![weather-mess](https://cloud.githubusercontent.com/assets/203767/13035325/a226df72-d34d-11e5-914d-1f3150829928.png)

The coordinates from both website and extension are the same (I edited the location coordinates in the extension).

As far as I understand, the arrow up indicates maximum temperature and the arrow down indicates minimum temperature expected.

If I’m not missing something, why is the maximum temperature (2.3℃) is lower than the present temperature (4.4℃)?

Sorry, but I simply don’t get it.

**Comment by jenslody** [comment]
You should ask at openweathermap.org.
The extensions just shows the values as I get them from their website, as you can see on the screenshot.
Maybe it was more warm in reality as they have expected in their forecast.

![Uploading Bildschirmfoto von »2016-02-14 20-39-23«.png…]()
