### ISSUE TITLE
Shows outdated infos/not updating current weather

### ISSUE THREAD

**Issue by snckrz** [jenslody/gnome-shell-extension-openweather#120]
Last refresh was at 16:16 (4.2°C), currently openweathermap.org shows 2.4°C for my place, and it got the data at 16:27. At the moment it's 16:35. It doesn't seem to refresh every 10 Minutes like the "refresh timeout for current weather" says. 
I'm using Arch Linux, this problem happens with both, the git version (installed from AUR) and with the version from the gnome extension page. Using Gnome 3.18.2

Edit: It refreshed and (atleast show that it) fetched the data from 16:30 (atm its actually 16:45) but its still showing 4.2°C.

**Comment by jenslody** [comment]
The refresh shown is the time I get from openweathermap.org inside the data, not the time when I asked for new data.

**Comment by jenslody** [comment]
There is nothing I can do, sorry.
