### ISSUE TITLE
Support for Gnome 3.20

### ISSUE THREAD

**Issue by unixfox** [jenslody/gnome-shell-extension-openweather#121]
[Gnome 3.20 was released](https://www.gnome.org/news/2016/03/gnome-3-20-released/) yesterday, can you update this extension for the new version ?
I just tested and this extension works fine under Gnome 3.20 by modifying `metadata.json`!

**Comment by jenslody** [comment]
It's in master and all actual Fedora repos and el7, partly in testing, partly already in stable.
