### ISSUE TITLE
Doesn't compile on FreeBSD

### ISSUE THREAD

**Issue by fb87** [jenslody/gnome-shell-extension-openweather#124]
I get the message:

./configure: 3051: Syntax error: word unexpected (expecting ")")

And please don't rely on bash, that's bad coding practice. Not every OS ships it (the BSDs e.g. prefer csh/tcsh/zsh) and I don't think you really can't go with sh.

**Comment by jenslody** [comment]
The only place I "relied" on bash (as far as I know) is the shebang of autogen.sh ,
The configure-script is generated by system tools when running gnome-autogen.sh from autogen.sh .
So I don't see what I can do here.

I just changed autogen.sh's shebang to use /bin/sh instead of /bin/bash .

**Comment by jenslody** [comment]
Does it work now.

**Comment by fb87** [comment]
Sorry, I don't have this system running anymore.
