### ISSUE TITLE
Show Fahrenheit temp in rounded values

### ISSUE THREAD

**Issue by hhhorb** [jenslody/gnome-shell-extension-openweather#128]
I'm in the U.S. where we use Fahrenheit, but nobody displays the temperature down to the tenth of a degree. Can I edit a file to display the temp in a rounded value (i.e. 79 F instead of 78.9 F).

Thanks for the help, great extension!

**Comment by jenslody** [comment]
You can either change it for all values in the preferences ("Layout"-tab) or change the toFahrenheit-function in extension.js, to use 0 as fixed length in line 1042.

**Comment by hhhorb** [comment]
Ah, I thought I had used this extension before and that there was a preference setting. Layout>Max digits after decimal>0 does the trick.

Issue SOLVED, thanks for the quick reply!
