### ISSUE TITLE
appears twice on header bar

### ISSUE THREAD

**Issue by jpritikin** [jenslody/gnome-shell-extension-openweather#131]
See the "31 C" twice? It should only be there once, I think.

http://imgur.com/wveHPBJ

This is gnome 3.20 on tanglu4 with openweather 0~20160325.gitb5415ec-1

**Comment by jenslody** [comment]
Is this permanent or can you "fix" it with restarting the gnome-shell, usually ALT+F2, then "r" and Enter, or log out and log in again on wayland).
Do you also have a local installation of the extension (in "~/.local/share/gnome-shell/extensions") ?

**Comment by jpritikin** [comment]
Oh! I restarted gnome-shell as you suggested and it seems to be fixed.
