### ISSUE TITLE
Add yr.no as datasource

### ISSUE THREAD

**Issue by HeikoAdams** [jenslody/gnome-shell-extension-openweather#135]
Yr.no is the free online service of the norwegian meteorological institute (met.no) and provides free weather data too. IMHO these data is more reliable then forecast.io or openweathermap

**Comment by jenslody** [comment]
Duplicate of #70 
No fix for this until now, if you (or somebody else) know(s) a free javascript xml-parsing library, that can be used from a gnome-shell-extension, I will add yr.no as weather-provider.
