### ISSUE TITLE
Popup menu's position

### ISSUE THREAD

**Issue by sharifzadesina** [jenslody/gnome-shell-extension-openweather#143]
Can we have the extension's pop-up menu like date-time menu in the center when _Position in Panel_ setting sets to center?

**Comment by jenslody** [comment]
It should be easy to make it configurable.

**Comment by sharifzadesina** [comment]
@jenslody 
Maybe but I don't know anything about gnome extensions...

**Comment by jenslody** [comment]
No problem, I will add an option to configure it as soon as possible.

**Comment by jenslody** [comment]
Newest revision with configurable position is in review on gnome-shell.org .
Zip-file for manual installation with gnome-tweak-tools: https://extensions.gnome.org/review/download/6141.shell-extension.zip

**Comment by sharifzadesina** [comment]
@jenslody thanks a lot
