### ISSUE TITLE
Ends up with the "refresh" icon showing a lot in the toolbar

### ISSUE THREAD

**Issue by autarch** [jenslody/gnome-shell-extension-openweather#147]
Often I'll look up and see the circular arrow refresh icon instead of the forecast. The vast majority of the time, if I click on the arrow and then click on it again the opened extension I get the weather updated.

I'm not sure why this happens so often. My guess is that maybe the data source is flaky or network issues interfere with an update. I'd suggest keeping the old weather status for at least a little longer and not showing the refresh icon until the refresh has failed several times in a row (or maybe just keep the old forecast for a certain period of time, like 2 hours?).

As an aside, showing the refresh icon in the toolbar and then having to click on that and _another_ refresh icon to refresh the data seems silly. If the toolbar shows a refresh icon, clicking on it should initiate a refresh.

**Comment by omeryagmurlu** [comment]
same, tried reistalling and can't install it anymore, it gives an error

**Comment by jenslody** [comment]
I can not reproduce this issue(s).
Which weather-provider do you use ?
@omeryagmurlu: what error is shown ?
@both: which version of the extension do you use, which version of gnome-shell and which linux distro ?

**Comment by autarch** [comment]
I've been using the default provider, which I assume is openweather.

**Comment by jenslody** [comment]
Yes, default is openweather.
I just pushed a fix for this to master.
It does not invalidate the shown weatherdata for openweathermap, until the extension gets a valid answer from their server.
Can you test it yourself ?
You can use the attached zip-file and install it with the "gnome-tweak-tool" or manually unzip it to "~/.local/share/gnome-shell/extensions/openweather-extension@jenslody.de/".
(I hope this works, it's the first time I attach a file here.)
[openweather.shell-extension.zip](https://github.com/jenslody/gnome-shell-extension-openweather/files/491297/openweather.shell-extension.zip)

**Comment by autarch** [comment]
I unzipped it to the ~/.local folder. Do you know if gnome-shell automatically reloads the extension? I went into the tweak tool and disabled then reenabled it as well.

**Comment by autarch** [comment]
This still seems to be happening with the code in the zip file.

**Comment by Leeo97one** [comment]
I can confirm that the issue is still present (also #152).

**Comment by jenslody** [comment]
I get this (with openweathermap.org) after a resume from sleep.
In this case it looks like the extension is restarted by the shell and if there is no valid data available I only get the refresh-symbol.
I don't see this with Dark Sky (former forecast.io), its seems their weather service is more reliable.
