### ISSUE TITLE
forcast.io API Change

### ISSUE THREAD

**Issue by CurtisLeeBolin** [jenslody/gnome-shell-extension-openweather#149]
The Forecast API is now The Dark Sky API.

http://status.darksky.net/2016/09/20/forecast-api-is-now-dark-sky-api.html

**Comment by cwmke** [comment]
This should be resolved with #148.

**Comment by CurtisLeeBolin** [comment]
Thank, @cwmke.  I planned to work on it but hadn't found time.  I built and tested it.  I see the dialog changes, and it works fine.
