### ISSUE TITLE
Bad or uncomplete Arabic and Bulgarian translations are breaking the RPM build

### ISSUE THREAD

**Issue by DevDef** [jenslody/gnome-shell-extension-openweather#154]
Hi,

When I try to build an RPM with the latest Git revision, it fails. I had to remove the first two lines (“ar” and “bg”) of the LINGUAS file to be able to build the RPM. Authors of these two translations should be contacted to fix them.

By the way, the PO template file is outdated. It has to be regenerated and msgmerge run again to reflect the change from “Dark Sky” to “darksky.net”.

Cheers,

Davy

**Comment by jenslody** [comment]
I updated the "Project-Id-Version"-Header in both files and in id.po.
I just build the extension for Fedora 25 and Rawhide (for gnome-shell 3.22) without error:
http://koji.fedoraproject.org/koji/packageinfo?packageID=21010 .
