### ISSUE TITLE
Configuration window hides add/remove buttons by default

### ISSUE THREAD

**Issue by lastorset** [jenslody/gnome-shell-extension-openweather#172]
The default size for the configuration window is too short, so the "+/-/Pencil" buttons at the bottom are not visible. Since the scrollbars are also invisible by default in my current theme, this led to a very confusing few minutes when trying to add my city!

![openweather preferences window too small](https://cloud.githubusercontent.com/assets/464989/21643983/751164f6-d28b-11e6-96b9-f611a0a4f3ca.png)

Probably the best fix is to enforce a minimum size of the window that keeps the buttons visible, and also reduce the minimum size of the list box.

(And now I suddenly realize that there is a dotted line to indicate a scrollable area.)

Ubuntu 16.10

**Comment by jenslody** [comment]
Forcing a min-size is not so easy, due to the way the prefs-window is created by gnome-shell.
I do not remember exactly if it does not work reliabel, because of nackwards-compatibility of my extension or because of gome-shell shortcomings.
Nevertheless, it's on my todo-list.

**Comment by lastorset** [comment]
Perhaps the list box could be allowed to shrink smaller? For instance to 3 lines of height. That way the buttons would be more likely to be visible.

**Comment by jenslody** [comment]
Easiest fix is to move the buttons from the bottom to the top, so they are always visible.
Or to have two sets of buttons, that do the same.

**Comment by jenslody** [comment]
Should be fixed in master. Min version of gnome-shell is now 3.14.
I could not test older versions, so I removed the compatibility flag to not break them.

**Comment by lastorset** [comment]
Tested master on 3.20, looks good. Thanks! :smile_cat:
