### ISSUE TITLE
Forks ...

### ISSUE THREAD

**Issue by TJProgrammer** [jenslody/gnome-shell-extension-openweather#174]
Hello!

A simple question:
Why do you create this fork?
Why do not join this fork with the Neroth main branch?

Thank you.

**Comment by jenslody** [comment]
Because Neroth switched to gnome-weather, which was unusable at this time (smaller cities and villages could not be used) and still is not reliable for the places I use and often not able to even find them.
My fork has diverged quiet far from Neroth's branch.
