### ISSUE TITLE
Text is not capitalised

### ISSUE THREAD

**Issue by amankhoza** [jenslody/gnome-shell-extension-openweather#179]
In the screenshots on the GitHub (Language=German) the text is capitalised, whereas on my machine (Language=English) the text is not capitalised. I think this should be a trivial fix. See image below:

![weather](https://cloud.githubusercontent.com/assets/5832764/23557279/786491fe-0027-11e7-8e9f-2515bb454ba8.png)

**Comment by TJProgrammer** [comment]
Hello @amankhoza !
It be seems a translation fix.
If more people wants this fix, I can update it...
What do you think @jenslody ?

**Comment by amankhoza** [comment]
I've fixed this issue locally, I just capitalised the strings in the getWeatherCondition() function in openweathermap_org.js. Looks much better IMO.
![screenshot from 2017-03-23 00-07-36](https://cloud.githubusercontent.com/assets/5832764/24226166/cf62fac4-0f5c-11e7-88de-d5e3a6725577.png)

**Comment by TJProgrammer** [comment]
How did you do that?
Did you add "capitalize" function in all returns?

**Comment by amankhoza** [comment]
@TJProgrammer I added a capitalize first letter function

`function capitalizeFirstLetter(string) {`
`    return string.charAt(0).toUpperCase() + string.slice(1);`
`}`

then I just ran the capitalizeFirstLetter function on the comment variables in parseWeatherCurrent and parseWeatherForecast, like so:
    `this._currentWeatherSummary.text = capitalizeFirstLetter(comment) + _(", ") + temperature;`
and
    `forecastUi.Summary.text = capitalizeFirstLetter(comment);`

**Comment by TJProgrammer** [comment]
OK. I understand you.
It is a interesting way to get it done. With this solution isn't necessary
ask to all for update all translations.
