### ISSUE TITLE
Decimal values should take care of the locale

### ISSUE THREAD

**Issue by DevDef** [jenslody/gnome-shell-extension-openweather#184]
All displayed decimal values should take care of the locale and have the correct decimal and digit group separators.
Now they are using the default C locale, but lots of countries use the comma as the decimal separator and a thin space as the digit group separators (see: https://en.wikipedia.org/wiki/Decimal_mark).

**Comment by DevDef** [comment]
You already use Number.toLocaleString(), but unfortunately without any argument this method use the default C locale instead of the user’s one. It seems that you have to give the locale to use as a string argument to the method (for example: 'fr').
I guess something like toLocaleString(this.fc_locale) would do the job.

**Comment by jenslody** [comment]
I will look into it this week.
Thank you for reporting it.

**Comment by DevDef** [comment]
Well, your extension is correctly displaying localized numbers without any arguments to the Number.toLocaleString() method on an old GNOME Shell 3.14 (Mageia 5), but wrongly displaying default C locale numbers on a brand new GNOME Shell 3.24 (upcoming Mageia 6).
So, I was wrong, it seems that the toLocaleString() method is supposed to use the user’s locale if no argument is given.
Now, I don’t know why the user’s locale is not set in GNOME 3.24 (for Mageia 6)…

**Comment by jenslody** [comment]
I will test it on Fedora 26 or Rawhide with 3.24 and different locales.

**Comment by DevDef** [comment]
Thank you Jens. FYI, I use GNOME 3.24 on Wayland. I suspect a bad inheritance of the user’s locale in the specific Wayland context.

**Comment by jenslody** [comment]
I could reproduce it and committed a fix for it to master.
A fixed version is in review on extensions.gnome.org and pushed to Fedora 26 and Rawhide (27).

**Comment by DevDef** [comment]
Thank you Jens.

BTW, the Number.toLocaleString() method with no argument should use the user’s locale like it did before. This regression should be reported upstream. Unfortunately, I don’t know where to report. If you have a better knowledge than me about which GNOME component has to be fixed, it would be nice of you to do the report.

**Comment by jenslody** [comment]
gnome-shell uses gjs and that uses mozjs the mozilla javascript engine.

Quote from [https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString](url):
> Note: ECMAScript Internationalization API, implemented with Firefox 29, added the locales argument to the Number.toLocaleString() method. If the argument is undefined, this method returns localized digits specified by the OS, while the previous versions of Firefox returned Western Arabic digits. This change has been reported as a regression affecting backward compatibility which might be fixed soon. (bug 999003)

Gnome-shell < 3.24 used mozjs24 and beginning from 3.24 it uses mozjs38.
So the behaviour might change again.

**Comment by DevDef** [comment]
So, IIUC, this is a well known 3 years old regression of the MozJS library!
The last (one month old) comment ([#57](https://bugzilla.mozilla.org/show_bug.cgi?id=999003#c57)) of the Mozilla Bugzilla [bug #999003](https://bugzilla.mozilla.org/show_bug.cgi?id=999003) gives a little hope that a fix will soon be released, though.

Anyway, thank you for these explanations.

Davy
