### ISSUE TITLE
shows wrong county for Brookline, MA

### ISSUE THREAD

**Issue by robatino** [jenslody/gnome-shell-extension-openweather#191]
This is a very minor issue, sorry if this is the wrong place to report it. Brookline, MA is in Norfolk County, not Suffolk County. (BTW, is it necessary to show the county at all? It might be better to just get rid of it in all the listings.)

**Comment by jenslody** [comment]
What you see is what the geolocation provider returns.
In your case it's openstreetmap's  nominatim.
Nothing I can change,
You can change the provider in the settings, but for mapquest, you need an api-key, they reurn: Brookline, Norfolk County, Massachusetts, United States of America [42.3317642,-71.1211635],
while geocode.farm does not return the county and openstreetmaps returns a wrong county.
Nevertheless, you can edit the returned value to show whatever you want, so as long as the coordinates are correct, this should not be a real problem.

**Comment by robatino** [comment]
I confirmed that searching for "Brookline, MA" at OpenStreetMap.org shows "Suffolk County". I will see if I can file a ticket with them. Thanks. Closing ticket.

**Comment by robatino** [comment]
Just FYI, problem fixed at the source - see https://help.openstreetmap.org/questions/56981/brookline-ma-is-in-norfolk-county-not-suffolk-county - and it shows the correct county now.
