### ISSUE TITLE
Search for location does not display any results on Wayland in Ubuntu 17.10

### ISSUE THREAD

**Issue by enolive** [jenslody/gnome-shell-extension-openweather#206]
Hi there,

I found a strange problem regarding this wonderful extension.
When working in a Wayland session, the search function that appears when trying to add a location won't display any results. Therefore, it seems to be impossible to add a new location in this display mode without fiddling with dconf.

How to reproduce:
- Open the settings dialog
- Click on '+' to add a new location
- Enter some city (say, New York)
- Click on 'Search'
- While this works perfectly on X.org, when using Wayland, no search results will be displayed.

**Comment by jenslody** [comment]
I just tried it on my system (Fedora 26) and it works as expected (except for the dialog size).
Which OS and version do you use ?

**Comment by henriAbel** [comment]
Also have same problem with latest Ubuntu 17.10 and Wayland. Impossible to add new location.

**Comment by enolive** [comment]
Thanks jenslody for the reply!
I am using Ubuntu 17.10 with Gnome 3.26 and OpenWeather from extensions.gnome.org on a Lenovo Laptop with integrated Intel GPU.
Please let me know if you need any further details!

**Comment by emagra** [comment]
+1 same problem. On Ubuntu 17.10 wayland and openweather version 91

**Comment by jenslody** [comment]
I will try to reproduce it in a vm.
I wonder what the Ubuntu devs do, they are known to break wxWidgets stuff with nearly any new release, but this is something new.
Do yu have any thing in the logs.
I don't know where they are on Ubuntu, on Fedor I use "journalctl -fln" and usually get something related in such cases.

**Comment by jenslody** [comment]
I was able t reproduce it in a vm, so I hope I will be able to debug and fix it.

**Comment by irakliy01** [comment]
I have same problem. Please, fix it

**Comment by jenslody** [comment]
I already wrote, that I try to fix this.
Please do not write "+1" or "I have the same issue" posts.
They are not helpful in any way.

If you do not have something meaningful to contribute, just do not post here.

**Comment by cicindel** [comment]
Search also doesn't work for me on Ubuntu 16.04 LTS with Gnome 3.18 and recent update of the extension (I updated few days ago). After typing location no results are shown for selection.

**Comment by jenslody** [comment]
I accidently broke compatibility with gtk < 3.22 when fixing this issue.
I fixed it yesterday and lcukily the uploaded version was reviewed really fast.
Thank you for confirming the fix.
