### ISSUE TITLE
Support adding own link to weather radar map

### ISSUE THREAD

**Issue by DanScharon** [jenslody/gnome-shell-extension-openweather#21]
In the old days of GNOME 2 and its weather applet, one could add a link to a weather radar map in the settings (usually to an animated gif showing a rain radar in a loop), so the image was integrated in the extended weather data view.

Please add this possibility to your Gnome Shell Extension as well.

Best,
Dan

**Comment by WyRe** [comment]
Still is not working this feature¿ :D

**Comment by jenslody** [comment]
This feature will not come, at least not in the near future.
To see the radarmap of openweathermap.org or forecast.io, just click on the link and view it in the browser.
Any attempt to place it into this extension does not make sense in my opinion, because it will always be much too small.
