### ISSUE TITLE
Slow to update and cannot update manually

### ISSUE THREAD

**Issue by bowren** [jenslody/gnome-shell-extension-openweather#28]
Hello, I use Debian Testing and installed this extension through its repository. Should be up to date, extensions.gnome.org does not report any updates available.

The problem is that the extension seems to lag behind the actual forecast on openweathermap.org for an hour or two. Also when it finally updates, it seems to update to another past weather report. I tried pressing the reload button to get the updates manually, but only sometimes it updates. This results in drastically different weather readings than the actual weather.

Perhaps there is a way to set the default reload time?

**Comment by jenslody** [comment]
You can now chose between openweathermap.org (which is unreliable/slow sometimes) and forecast.io.
I close this issue therefore.
