### ISSUE TITLE
 And openweathermap.org weather data inconsistency?

### ISSUE THREAD

**Issue by gmg137** [jenslody/gnome-shell-extension-openweather#29]
![](http://git.oschina.net/uploads/images/2014/1026/110834_0f1533dd_24256.png)
![](http://git.oschina.net/uploads/images/2014/1026/110828_b3d92745_24256.png)

**Comment by jenslody** [comment]
You can now chose between openweathermap.org (which is unreliable/slow sometimes) and forecast.io.
I close this issue therefore.
