### ISSUE TITLE
Wrong city is selected

### ISSUE THREAD

**Issue by kleinph** [jenslody/gnome-shell-extension-openweather#30]
When I enter _Illmitz_ it shows me `Illmitz, AT [3052640]` but it turns to `Illmitz (HU)` after I select it.
On openweathermap.org Illmitz is listed with [2775327](http://openweathermap.org/city/2775327) and [3052640](http://openweathermap.org/city/3052640) is Fertorakos - a city in Hungary aprox. 10km away.

**Comment by jenslody** [comment]
I chaned the search and use openmapquests implementation of openstreetmaos nominatim (https://open.mapquestapi.com/nominatim/) for search, you can now use more exact terms (streets, zip-codes, coordinates etc.).
I close this issue therefore,
