### ISSUE TITLE
Please add mmHg as pressure unit

### ISSUE THREAD

**Issue by crayxt** [jenslody/gnome-shell-extension-openweather#33]
Although it is not SI unit, mmHg is still commonly used. It would be nice to see Pressure measured in mmHg. I suppose it is relatively easy to convert from inHg.

Thanks,

**Comment by 13xforever** [comment]
I second this request. mmHg is the only widely-used unit here where I live, so it will be very much appreciated.

**Comment by jenslody** [comment]
Added in master.
