### ISSUE TITLE
insufficient info for cities in US

### ISSUE THREAD

**Issue by hcmeyer** [jenslody/gnome-shell-extension-openweather#34]
I live in a small city, Shelbyville, in KY in the US. There are two other cities with the same name in Indiana and Tennesse. I cannot tell which Shelbyville I am receiving weather reports for, the extension says "Shelbyville (US)". Similar problem for nearby city, Frankfort, in KY and in Michigan. Frankfort KY has an airport with an official FAA weather station, so is a good data source..

**Comment by jenslody** [comment]
I chaned the search and use openmapquests implementation of openstreetmaos nominatim (https://open.mapquestapi.com/nominatim/) for search, you can now use more exact terms (streets, zip-codes, coordinates etc.).
I close this issue therefore,
