### ISSUE TITLE
Plural form for "In %s days"

### ISSUE THREAD

**Issue by prescott66** [jenslody/gnome-shell-extension-openweather#42]
please can you make plural form for this string:

#: ../src/extension.js:1463
#, python-format
msgid "In %s days"

**Comment by jenslody** [comment]
Sorry for the late reply.
I do not understand what the problem is, and what I should change, sorry.

**Comment by prescott66** [comment]
This should helps you to understeand:

https://wiki.gnome.org/TranslationProject/DevGuidelines/Plurals

**Comment by jenslody** [comment]
Thanks for the link.
At the moment I don't know how to do this with javascript, but I will try to find a solution.

**Comment by jenslody** [comment]
I works no in actual master.
