### ISSUE TITLE
Backend so unreliable ...

### ISSUE THREAD

**Issue by tkelley65** [jenslody/gnome-shell-extension-openweather#43]
Can we have a choice of backends? Openweathermap seems to be in and out all the time. I went an got an API key, and that helped when using the website, but the shell extension doesn't seem to have benefitted from it. As it is, the backend is just completely non-functional.

**Comment by jmo707** [comment]
I suffer from this too. The current weather conditions shown are usually *plain* wrong, and getting a (free) API didn't make any difference for the plugin. I've seen comments like this on the Gnome Extensions page too.

**Comment by jenslody** [comment]
You can now chose between openweathermap.org (which is unreliable/slow sometimes) and forecast.io.
I close this issue therefore.
