### ISSUE TITLE
Network error tolerance

### ISSUE THREAD

**Issue by Hexcles** [jenslody/gnome-shell-extension-openweather#44]
Last weekend, Openweathermap.org had a major API outage (well, according to its official Twitter account, it was not down but just "slow"). And I could only see "loading" in the widget. Even one request was fortunately successful, the data only showed up a very short period of time and became "loading" again (might because of the previously piled-up requests).

I think a better approach to become more tolerant with network error would be like this: don't throw away old data immediately after starting a new request. We can add a "(loading)" prompt AFTER the current data so that users can still see old data during network requests. Furthermore, we can add "last updated at ..." to the detail view.

**Comment by jenslody** [comment]
You can now chose between openweathermap.org (which is unreliable/slow sometimes) and forecast.io.
This does not change the behaviour, but gives a workaround.

**Comment by ronjouch** [comment]
@jenslody in my case, neither openweathermap nor forecast.io work, even using proper API keys for each. The last few weeks I've just been seeing *"Loading current weather..."* :-/ . Any idea?

* Extension was installed via extensions.gnome.org
* Restarting Shell / system doesn't help
* The "show errors" link of the extension in the `lg` panel is empty
* Using GNOME 3.16.1 under Arch Linux
* I can provide more debug info if needed

Thanks for the extension!

**Comment by SvetlinZarev** [comment]
@ronjouch Try deleting your locations and then adding them again. It worked for me.

**Comment by ronjouch** [comment]
Yay @SvetlinZarev that worked! Thanks for the tip :+1: , proposing an addition to README.md

**Comment by DreaminginCodeZH** [comment]
Another possibility I encountered is that if you have some unsupported geo coords, the extension will always be in the loading state.

And this can easily happen if you try to set cities via dconf-editor or gsettings (when search is down), because the coords given on the city page of openweathermap.org puts longitude first, while in this extension you should put latitude first.

**Comment by jenslody** [comment]
Manual editing without deeper knowledge does not make sense.

The extension should not try to refresh weather, if there is no working internet connection, with recent versions.
Nevertheless, a broken server might still be a problem and it is not easy to fix, at least not without greater changes to the extension, which might lead to new errors.
So I close this bug.
