### ISSUE TITLE
Error on upgrade 

### ISSUE THREAD

**Issue by OneKorg** [jenslody/gnome-shell-extension-openweather#47]
I'm on gnome 3.12

![screenshot from 2015-04-06 22 28 38](https://cloud.githubusercontent.com/assets/7422005/7017452/60216af4-dcac-11e4-928b-585d1175c46f.png)

is there any more info I could provide that would be helpful?

**Comment by pacovila** [comment]
Same here with gnome 3.10 on Ubuntu 14.04 TLS

**Comment by chekavy** [comment]
Same error in Fedora 21 with GNOME 3.14

**Comment by Hexcles** [comment]
Error message:
`Expected type utf8 for Hash element but got type 'undefined'`

**Comment by Hexcles** [comment]
I tried to reset (delete) the extension's dconf keys, no use.

However, after adding a new city and fill in all the information. It's now working normally. Perhaps something wrong with the default values.

**Comment by chekavy** [comment]
https://extensions.gnome.org/extension/750/openweather

> **jens**
> I use it on Fedora 21 and it works. But one very important thing I forgot (sorry, it was late last night): all existing locations do not work anymore. If possible delete them all and recreate the entries. The extensions uses coordinates instead of openweathermap's id's now. I very much apologize for any problems related to this.

This is working for me.

**Comment by jenslody** [comment]
As posted on the gnome.org-site (cited by chekavy), the old entries are not compatible with the new ones, so you either have to edit them (if you know the coordinates) or delete and recreate them.
Nevertheless the "utf8"-error should not occur and should be fixed in master (and version uploaded for review)
