### ISSUE TITLE
Hangs downloading current weather

### ISSUE THREAD

**Issue by mjsaltzman** [jenslody/gnome-shell-extension-openweather#54]
Using with GNOME 3.16 from Fedora 22, but this has been an issue for a few releases.  On (only) one of my machines, the old weather app stopped updating weather and constatnly shows "loading current weather" in the status bar, even if I try to update manually. When I switched to the OpenWeather app, the problem persisted. Uninstalling and reinstalling doesn't help.  The problem occurs with openweathermap.org and with forecast.io.

Any idea where to look to find the problem?

**Comment by jenslody** [comment]
On Fedora you can open a terminal, run "journalctl -fln" and restart the shell ("Alt+F2" the "r" and "Enter") and see if you get a meaningful output related to openweather.
By the way: are you aware that you have to use forecast.io with an API-key or it does not load ?

**Comment by mjsaltzman** [comment]
Thanks.  I have API keys for both openweathermap and forecast.  Restarting the shell produced the messages below.  I also notice that the pop-down menu doesn't update if I click a different location, but opening the settings window shows that the location did change.

Below the first group of messages is a line of ======. Below that are the messages from opening the settings window.

Jun 06 14:56:01 paladin.localdomain gnome-session[2414]: Window manager warning: CurrentTime used to choose focus window; focus window may not be correct.
Jun 06 14:56:01 paladin.localdomain polkitd[958]: Unregistered Authentication Agent for unix-session:1 (system bus name :1.59, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.utf8) (disconnected from bus)
Jun 06 14:56:02 paladin.localdomain gnome-session[2414]: current session already has an ibus-daemon.
Jun 06 14:56:02 paladin.localdomain polkitd[958]: Registered Authentication Agent for unix-session:1 (system bus name :1.119 [/usr/bin/gnome-shell], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.utf8)
Jun 06 14:56:02 paladin.localdomain gnome-session[2414]: Gjs-Message: JS WARNING: [/home/mjs/.local/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com/extension.js 868]: anonymous function does not always return a value
Jun 06 14:56:02 paladin.localdomain gnome-session[2414]: Gjs-Message: JS LOG: System monitor applet init from /home/mjs/.local/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com
Jun 06 14:56:03 paladin.localdomain gnome-session[2414]: Gjs-Message: JS LOG: System monitor applet enabling
Jun 06 14:56:03 paladin.localdomain gnome-session[2414]: Gjs-Message: JS LOG: System monitor applet enabling done
Jun 06 14:56:03 paladin.localdomain gnome-session[2414]: (gnome-shell:2655): GLib-GObject-WARNING **: The property GtkContainer:resize-mode is deprecated and shouldn't be used anymore. It will be removed in a future version.
Jun 06 14:56:03 paladin.localdomain gnome-shell[2655]: GNOME Shell started at Sat Jun 06 2015 14:56:02 GMT-0400 (EDT)

============================

Jun 06 14:57:17 paladin.localdomain gnome-session[2414]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x2400005 (GNOME Shel)
Jun 06 14:57:17 paladin.localdomain gnome-session[2414]: Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Jun 06 14:57:17 paladin.localdomain gnome-session[2414]: Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

**Comment by rrakich** [comment]
I had to remove the old location definitions and re-add them after the upgrade and changing to forcast.io, then everything worked correctly.

**Comment by jenslody** [comment]
After update from to revision >= 29 (of my extension) you have to readd the locations as described in the wiki, the readme and on the gnome.org-site.

**Comment by mjsaltzman** [comment]
Deleting and re-adding locations had not worked for me in the past, but it did this time.  Thanks.
