### ISSUE TITLE
Cache and show last known weather when offline

### ISSUE THREAD

**Issue by jancborchardt** [jenslody/gnome-shell-extension-openweather#57]
On startup or return from suspend, you’re always greeted with »Loading weather …« in the top bar, which is a tad annoying. Instead of that, the indicator could cache and show the last known weather.

**Comment by jenslody** [comment]
This is related to #72 . I work on a fix for it.

**Comment by jenslody** [comment]
Should be fixed in latest master-branch, on extensions.gnome.org and in my fedora repo.

**Comment by jancborchardt** [comment]
Thank you! :)
