### ISSUE TITLE
OpenWeather does no more work in Debian

### ISSUE THREAD

**Issue by vporton** [jenslody/gnome-shell-extension-openweather#58]
gnome-shell-extension-weather 0~20150615.git0162cf7-1 running on "testing" ("stretch") Debian Linux stopped to work. Pressing "reload" button does not help. Switching between openweathermap.org and forecast.io does not help.

Screenshot: https://bug751564.bugzilla-attachments.gnome.org/attachment.cgi?id=306188

**Comment by jenslody** [comment]
Did you try to delete and recreate the locations as decribed in the Redme and wiki here and on https://extensions.gnome.org/extension/750/openweather/ ?

**Comment by vporton** [comment]
Yes, this helps. Thanks.
