### ISSUE TITLE
Truncate location name

### ISSUE THREAD

**Issue by lightonflux** [jenslody/gnome-shell-extension-openweather#60]
When using forecast.io the name of the city/town can get ridiculous long, it would be nice if it was shorter like "City, Country".

At the moment it is:

"Town, Address of Station, Town, administrative district, federal state, Post code, Country"

![bildschirmfoto von 2015-07-11 12 13 07](https://cloud.githubusercontent.com/assets/1377943/8633400/ca788a1c-27c6-11e5-9420-747abf90e3d6.png)

**Comment by jenslody** [comment]
Which revision do you use, since several revisions you can edit the location name in the preferences.

**Comment by jenslody** [comment]
ping

**Comment by lightonflux** [comment]
Afaik i now use the newest version. I already renamed it. When i reported the bug i used the version from Debians repo. Which has this version 20140924.git7e28508 in stable. 

Thanks for pinging.
