### ISSUE TITLE
Version 1-0.1.20150814.gitab4f945.fc22.noarch does'n work

### ISSUE THREAD

**Issue by alh54** [jenslody/gnome-shell-extension-openweather#65]
I use Fedora22 with Gnome 3.16.2, I have installed gnome-shell-extension-openweather from from jeanlody repository. Since the last update the weather applet doesn't work and i can't activate the extension with gnome-tweaktool.
I had to downgrade to 1-0.1.20150726.gite139cf7.fc22.noarch version, that works fine.
Thank you.

**Comment by jenslody** [comment]
Already fixed.

**Comment by alh54** [comment]
Thank-you for your prompt response.
