### ISSUE TITLE
Updated openweather extension crashes

### ISSUE THREAD

**Issue by wdneumann** [jenslody/gnome-shell-extension-openweather#66]
Openweather preferences crashes whenever I try to create or update locations to the new version of the extension. Uninstalling and re-installing the extension does not help. 
My installed locations are not erased when I uninstall the extension. Deleting them might help, but I can't find where they are installed to delete them.

**Comment by jenslody** [comment]
Does deleting the locations with the "-"-button not work ?
You can remove the whole configuration of openweather from a console with "dconf -f reset /org/gnome/shell/extensions/openweather/" or just the locations with "dconf reset /org/gnome/shell/extensions/openweather/city".

**Comment by pdrocaldeira** [comment]
Same here.
And to remove my config I used ""dconf reset -f /org/gnome/shell/extensions/openweather/"  (-f after reset).
