### ISSUE TITLE
data refreshment interval?

### ISSUE THREAD

**Issue by ousia** [jenslody/gnome-shell-extension-openweather#71]
@jenslody, is there an automatic data refreshment interval when not using personal API keys?

I think that it would be a nice feature to be implemented.

**Comment by jenslody** [comment]
The data refreshment interval is the same with and without api-key: 10 minutes for the actual weather and 10 minutes for the forecast.
It can be changed in dconf, but I can (and will) add this to preferences.

**Comment by ousia** [comment]
@jenslody, many thanks for your reply. I have just changed values with dconf-editor.

BTW, default refreshment interval for the forecast is one hour (3600 secs).

**Comment by jenslody** [comment]
You can now change the refreshment intervals from the preferences dialog.
