### ISSUE TITLE
Frequent system UI freezes

### ISSUE THREAD

**Issue by SangSatori** [jenslody/gnome-shell-extension-openweather#76]
I'm experiencing full interface freezes (as in, whole Gnome Shell freezes) after installing the extension. Weather information gets retrieves successfully, but something's blocking the screen redraws from time to time.

I'm running Fedora 22 with Gnome 3.16.

If there's some more information or logs I could provide, I'd be happy to.

**Comment by choma** [comment]
Awesome catch!! I have been thinking it was a gnome-shell problem.
I'm on Debian Jessie, using gnome 3.16 and 3.18 since a couple of days. I just disabled this extension and the freezes stopped.

I'll be happy to provide any info too.

**Comment by jenslody** [comment]
Do you use the version from debian repo ?
Or from extensions.gnome.org or directly from this side ?

**Comment by choma** [comment]
I use the version from debian repo. Here is the `aptitude show` output:

```
Paquete: gnome-shell-extension-weather           
Estado: instalado
Instalado automáticamente: sí
Versión: 0~20151003.git339ec8a-1
Prioridad: extra
Sección: gnome
Desarrollador: Debian GNOME Maintainers <pkg-gnome-maintainers@lists.alioth.debian.org>
Arquitectura: all
Tamaño sin comprimir: 440 k
Depende de: dconf-gsettings-backend | gsettings-backend, gnome-shell (>= 3.12), gnome-shell (< 3.19), gir1.2-clutter-1.0, gir1.2-glib-2.0, gir1.2-gtk-3.0, gir1.2-soup-2.4
Recomienda: gnome-tweak-tool
Descripción: weather extension for GNOME Shell
 gnome-shell-extension-weather is a simple extension for displaying weather conditions and forecasts in GNOME Shell, featuring support for multiple locations, an easy way
 of selecting locations, and a settings panel through gnome-shell-extension-prefs. The weather data are fetched from Yahoo! Weather, and include forecasts for up to five
 days.
Página principal: https://github.com/jenslody/gnome-shell-extension-openweather
```

**Comment by jenslody** [comment]
I also use the extension (obviously) on Fedora 22, and for testing on F20, F21, F23 and F24 but never experienced such issues.
How often does this happen ?
Can you see anything in the logs, if the freeze occurs.
On Fedora just run "journalctl -fln" as normal user, on Debian: I can not remember at the moment where the logs go, sorry.

**Comment by SangSatori** [comment]
I've switched to primarily using Arch (Gnome 3.18) now, and the freezes are still there - cursor can be moved, music and background processes continue, but the whole shell and all applications freeze every few seconds. I looked at `journalctl -fln` output and did not see anything indicating errors (only thing related to my Dropbox instance) and Looking Glass debugger was unable to show any errors in the extension either. I'm using the extension from Gnome Extensions site.

Perhaps this is related to default configuration settings? I've not used the extension before, so it's at default values for me. Still, freezes should not happen and/or there should be an error emitted.

As always, if there's something I could inspect, I'd be happy to.

**Comment by choma** [comment]
I have reactivated the extension, and it isn't working now, even when I have a forecast.io key.
I deleted and created the location again, and then I got this in the logs:

```
Oct 17 09:21:21 choma gnome-session[3397]: Gjs-Message: JS WARNING: [/usr/share/gnome-shell/extensions/openweather-extension@jenslody.de/extension.js 415]: setting a property that has only a getter
Oct 17 09:21:21 choma gnome-session[3397]: (gnome-shell:3510): Gjs-WARNING **: JS ERROR: TypeError: coords.search is not a function
Oct 17 09:21:21 choma gnome-session[3397]: OpenweatherMenuButton<.extractCoord@/usr/share/gnome-shell/extensions/openweather-extension@jenslody.de/extension.js:827
Oct 17 09:21:21 choma gnome-session[3397]: wrapper@resource:///org/gnome/gjs/modules/lang.js:169
Oct 17 09:21:21 choma gnome-session[3397]: OpenweatherMenuButton<.locationChanged@/usr/share/gnome-shell/extensions/openweather-extension@jenslody.de/extension.js:480
Oct 17 09:21:21 choma gnome-session[3397]: wrapper@resource:///org/gnome/gjs/modules/lang.js:169
Oct 17 09:21:21 choma gnome-session[3397]: @/usr/share/gnome-shell/extensions/openweather-extension@jenslody.de/extension.js:423
```

I'm not sure if this is related.

On the other hand, as the weather isn't been loaded, the shell isn't freezing.

**Comment by jenslody** [comment]
The issue in the debian-version (no setter-function)  is already fixed on github, gnome.org and Fedora (update-testing).
It should not be related to ui-freezes anyway.

**Comment by jenslody** [comment]
This should be fixed in master (and on gnome.org).
See #82
