### ISSUE TITLE
Use this extension all the time. Today it quit working

### ISSUE THREAD

**Issue by meanbunny** [jenslody/gnome-shell-extension-openweather#77]
Anyone else having issues with the weather plugin today?

I get the following in /var/log/syslog, any other error locations to check?
Extension "openweather-extension@jenslody.de" had error: TypeError: coords.search is not a function

Tried using both forecast.io and openweather.org. Also tried a re-install and a reboot.

**Comment by mudongliang** [comment]
Same with you.
I use archlinux as my system.Today I just upgraded my gnome to 3.18. When I rebooted , I found openweather can't work. I was sure about connection to the Internet.
![screenshot from 2015-10-10 00-20-27](https://cloud.githubusercontent.com/assets/6214861/10399350/bf47ae2e-6ee4-11e5-8e27-7e2a680cbaab.png)

**Comment by meanbunny** [comment]
yeah its definitely related to the plugin. I am running Ubuntu 15.04 ​GNOME
3.16.

**Comment by jenslody** [comment]
No, it's not definitely related to the extension !
I just run it on gnome 3.16 and 3.18 without issues (Fedora 22 and 23).
I had issues with openweathermap today, but forecast.io works.
"coord.search is not a function" means that for some reason there is no valid city selected.
This can happen, if there is no location in the list
Reselecting one or adding a new one might help.
Deleting all locations and readding them (or at least one) can fix this, but I would like to know what happens, so I can try to fix it.
But as written, I don't have this issue, so it's hard to debug.

**Comment by meanbunny** [comment]
Ah ok, well let me re-install it and see if I can get forecast.io working
now. I tried forecast.io as well and it could find locations but not poll
any weather data.

Thanks,
Steven Combs
Meanbunny LLC, Owner
404-259-1118

**Comment by jenslody** [comment]
Neither forecast.io, nor openweathermap.org are used to search for locations in recent versions.
This is done with openstreetmaps nomination, geocode.farm or openmapquests nomination (the latter needs an api-key).

**Comment by meanbunny** [comment]
Ah gotcha, I wasn't aware of that.

Thanks,
Steven Combs
Meanbunny LLC, Owner
404-259-1118

**Comment by alijan92** [comment]
Latest Gnome 3.18, Fedora 23 Beta. Plugin stopped to work a few days ago...

**Comment by jenslody** [comment]
What exactly does not work ?
Which version of the extension do you use ?
Where did you get it from ?
If you use openweathermap and it just not loads, you should try forecast.io, if it's okay for you to register on their site and fetch an api-key.
If you do so, there is no need to provide billing data on their site !

I use the extension without issues on F23, F22, F21 and rawhide.

**Comment by jenslody** [comment]
It looks like you now need an api-key for openweathermap.org also.
They recommended it in the past, but now it seems to be required to work reliably.

**Comment by chekavy** [comment]
Same issue on Fedora 22, Gnome 3.16.

![screenshot from 2015-10-10 12-19-31](https://cloud.githubusercontent.com/assets/10311057/10410674/4fe2feca-6f49-11e5-915c-d183002497cc.png)

**Comment by beanaroo** [comment]
I just did a fresh Arch install and it seems openweathermap.org is not working without an API-key. Strange. I was using the extension on my previous install a few hours ago without one just fine.
I just started using forecast.io and the forecasts are much nicer. Worth signing up for.

**Comment by Scholars-Mate** [comment]
Adding a personal API-key fixed the issue for me. Looking at Open Weather Map's twitter, [they are now restricting keyless requests.](https://twitter.com/OpenWeatherMap/status/652672898327384064)

**Comment by meanbunny** [comment]
Ah nice, I will pick one up then and re-install the plugin. Thank you Chris!

Thanks,
Steven Combs
Meanbunny LLC, Owner
404-259-1118

On Sat, Oct 10, 2015 at 10:28 AM, Christopher Wong <notifications@github.com

**Comment by mudongliang** [comment]
![screenshot from 2015-10-11 12-06-57](https://cloud.githubusercontent.com/assets/6214861/10414623/9ee4ba32-7010-11e5-9d00-41fcb1b9da9c.png)

add a personal key here?

**Comment by jenslody** [comment]
Yes !

**Comment by Stechpalme** [comment]
Yes picking up a API key and re-install the plugin this seems to be the solution :)

**Comment by jenslody** [comment]
Reinstallation should not be needed.

**Comment by Quanttek** [comment]
Added API key for openwheathermap.org and it worked for a minute, but then the infamous "Loading..." appeared again

**Comment by chekavy** [comment]
> Added API key for openwheathermap.org and it worked for a minute, but then the infamous "Loading..." appeared again

+1

**Comment by jenslody** [comment]
Did you try forecast.io ?
It seems to be more reliable for the most users.

**Comment by spotman** [comment]
:+1: for this issue! To fix it you need to add API key + disable/enable this extension in GNOME Tweak Tool (you may find it via "CMD" key). Setting API key without reloading plugin did not worked for me.

**Comment by chekavy** [comment]
> Did you try forecast.io ?

No.
But right now extension is working correct with API key for http://openweathermap.org.

**Comment by jenslody** [comment]
It looks like a change of the weather.provider behaviour and not a "real" issue of the extension. At least nothing I can change, except staing this in the docs, what I did already.
So I close this bug.

**Comment by mudongliang** [comment]
I update the extension, then register myself in the openweathermap.org and get my personal API key. After adding the API key in the configuration, it works fine now.
Thanks.

**Comment by ian-abbott** [comment]
@jenslody: Have you seen [Q: API calls return an error 401](https://openweathermap.org/faq#error401)? It seems you should be able to register an API key built  in to the extension since it is a FOSS application.

**Comment by jenslody** [comment]
Thanks for the hint, I did not read it.
I just send a mail via their contact-form.
Let's wait what happens.
