### ISSUE TITLE
The Extension causes gnome shell to hang when no Internet is available

### ISSUE THREAD

**Issue by lviggiani** [jenslody/gnome-shell-extension-openweather#82]
Description:

Whenever my laptop is connected to a wifi hotspot (I tried with two different ones) but the hotspot is not connected to the internet (e.g. ISP is down, internet cable is disconnected or router is down or phone cable is not connected etc) gnome hangs. The mouse moves but noting else happens. This happens only within a Gnome session (after login), gdm works fine.

Steps to reproduce:
1) Turn on your computer and have it connected to a wifi hotspot.
2) at GDM, disconnect your hotspot from internet (e.g. disconnect the Internet cable or turn off the modem or disconnect the phone cable)
3) Login

The grey backgound appear. The mouse pointer appears and moves. Gnome just freezes.

4) While in that situation, turn off computer wifi (e.g. with fn keys or put it in ariplane mode)

Gnome comes to life again and works fine.

5) Try to tun on wifi again... after it reconnectes, gnome freezes again

If you disable the extension and repeat the setps above, it works fine. I'm running version 48 form extensions.gnome.org

**Comment by lviggiani** [comment]
same issue with latest version from git

**Comment by jenslody** [comment]
Thanks for the detailed description.
Unfortunately I can not reproduce it.
So some questions to have same conditions:
which OS do you use ?
which version of gnome-shell ?
is it OS-default or from a special repo ?
do you just have the local-version installed (of the extension), or also a system-wide one from any repo ?
do you have Neroth's gnome-shell-extension-weather installed ?
which api-keys are set ?

**Comment by lviggiani** [comment]
Hi,
here the the anwers
1) ArchLinux x64
2) GS 3.18
3) Default, up-to-date
4) Local version
5) I had the version installed from extension.gnome.org; then I removed it and installed from git (this one) with ./configure && make local-install
6) I've set the API key for openweathermap.org (also set as provider) and I'm using geocode.farm as geolocation provider

**Comment by burdges** [comment]
I've noticed GNOME Shell hanging when running this extension, but never conclusively shown the extension caused the problem.  I can however tell you how to reproduce the bug : 

First, install Tor, preferably via the Tor Project's ppa, but the Tor installed in Debian should work too.  And make sure systemd is starting it properly.  Just fyi you can see the system Tor's log with  `cat /var/log/tor/log`

Next, configure GNOME Shell to use Tor by going to Settings->Network->Network Proxy and setting the Socks host to 127.0.0.1 on port 9050.  you might need to restart GNOME Shell to make the extension use Tor.

Finally, kill tor with `systemctl restart tor` or `ps ax | grep tor` and `kill` or whatever.  GNOME Shell will freeze. 

I haven't yet tried this with the extension disabled, but it reliably nukes GNOME Shell on my machine running Debian Jessie.

**Comment by jenslody** [comment]
I only use Debian on testing vm's and on my wifes computer.
I just tested it on Fedora and did not get a hang, just not loading weather.
I will now test it on my Debian Jessie vm.

**Comment by burdges** [comment]
Alright, but my point is : There is a good chance you can reproduce the bug on any distribution by first routing all GNOME traffic through a socks proxy like Tor, and then killing the proxy process while in use.

I'll try to crash my GNOME Shell without the extension installed today and report back.

**Comment by bowren** [comment]
I too noticed gnome shell hangs when the extension is installed, though I can't be 100% certain that the extension was the cause of the problem. With the older version of the extension in the Debian repository, I never had gnome shell hang.

I just uninstalled the extension and I am checking how gnome behaves. I have done some initial tests. What I am certain about is that when the extension is installed:
1. gnome shell seems to hiccup around the time of establishing a network connection after resuming from suspend.
2. gnome shell seems to hiccup around the time of unlocking the lock screen after resuming from suspend.

**Comment by jenslody** [comment]
Unfortunately, I'm still not able to reproduce this issue, so I really don't know where to start.

**Comment by DeadMetaler** [comment]
Fedora 23 & Arch Linix
Gnome Shell 3.18
Disable connection internet and try to gdag winow. Connetc to internet and try it too. It's freeze for 3-5 seconds. Same problem sfter starting Gnome with autologin. Freezing  until it refreshes weather. If i disable extension, then all working excellent.

**Comment by jenslody** [comment]
Which window do you try to drag ?
Any window ?

**Comment by DeadMetaler** [comment]
Any window. Only mouse cursor moving without problem.

**Comment by jenslody** [comment]
I still can not reproduce it.
The only idea I have, is that for some reasons the httpsession of libsoup does not work in async-mode.
Can anyone with the issue look which version of libsoup is installed ?
And which version of the extension is in use.
If it's not in the about-tab (or the tab does not eexist), you find it in metadata.json in the rott-folder of the extension, either in ~/.local/share/gnome-shell/extensions/openweather-extension@jenslody.de/ or in /usr/share/gnome-shell/extensions/openweather-extension@jenslody.de/ .
If both are present, the first should have precedence.

**Comment by bowren** [comment]
At least for me it seems the complete freezes were due to a kernel issue with my initialization program (libreboot), so complete freezes are not due to the extension. The two points I listed about "hiccuping" are still present. It seems to be caused by network manager connecting to a network, and it only lasts as long as it takes to connect. I don't know if it is still helpful, but I have libsoup 2.48. I was using the latest version of the extension, so unless it was updated just a few days ago I was using version 50.

**Comment by DeadMetaler** [comment]
libsoup 2.52.1
openweather v. 50

**Comment by jenslody** [comment]
Can anyone of the users with the blocking/hickup issue testi the newest master, either by installing it with autotools as decribed in the wiki, or just by copying the new extension.js over the old one (this only works if the installation is new enough).
Don't  forget to make a backup before.

**Comment by mswal2846** [comment]
I initially thought that Bowren was right in that it seemed to be a Network Manager issue, but I had the extension active and when I tried to switch WIFI hotspots, the system paused until the connection was made.  So I then disabled the weather extension and switched WiFi hotspots and NO system pause what so ever.   So it does seem to be the weather extension.

Where do I get the newest master?  I'll test it out.

**Comment by bowren** [comment]
You are correct, I still experience this issue. In my last post I just said that complete gnome shell hangs are not due to the extension. The short pauses still seem to be due to the extension. I'll try out the latest master too.

mswal2846 just clone this repo. It seems jenslody commited the change just recently.

**Comment by bowren** [comment]
The issue seems to be fixed. I don't experience hiccups anymore. Good work Jens.

**Comment by jenslody** [comment]
This sounds good, so it was the connection test-method, which was not asynchronously.
It does not open a real connection, but according to the docs, it makes a dns-call, which might block.
I use a dns-cache on my system, so neither my main-system, nor any of my vm's have been affected.
I will push a new version of the extension for review on extensions.gnome.org this evening, if there comes no negative feedback.

**Comment by iNZT** [comment]
I have same issue when i am connecting to wifi or wifi disconnect or wifi signal is not stable
Gnome shell freeze for 3-15 sec, only cursor can move.
4.2.5-1-ARCH, GNOME SHELL 3.18

**Comment by DeadMetaler** [comment]
Yes. It's fixed from master branch.

**Comment by jenslody** [comment]
I just uploaded the latest version for review on extensions.gnome.org .

**Comment by jenslody** [comment]
The version with the fix is available at https://extensions.gnome.org/extension/750/openweather/ .

**Comment by irenge** [comment]
that freezing stuff i spend like 2 days trying to figure out what causing my fedora 23 freezing on gnome and other desktop except LXDE , decided to switch to LXDE until i sort it out or i get mysel helped my some expert in the matter, any help ?

**Comment by jenslody** [comment]
Wich version of the extension do you use (and from where).
You can see this on the about-tab (last tab) in the preferences or in the metadata.json-file, either in "~/.local/share/gnome-shell/extensions/openweather-extension@jenslody.de/" or "/usr/share/gnome-shell/extensions/openweather-extension@jenslody.de/" .

**Comment by irenge** [comment]
Sorry i don t know which version i used . it just started after i  copy a folder content proj from usr/local/share to /usr/share/  , then update , try to delete but it can not help
 As you have uploaded , we can just update and it will come as an update .

**Comment by jenslody** [comment]
Try to delete all references to the extension (preferences are stored by dconf and will stay) and isnatll it either from Fedora repo or from extensions.gnome.org.
Both versions should work without this issue.

**Comment by irenge** [comment]
u mean i empty /.local/share/gnome-shell/extensions/

**Comment by alex-eri** [comment]
i spent year with freezing shell... now i found this tread.
openwether from extensions.gnome.org stil freezes shell on archlinux and debian wheezy/jessie/stretch with gnome 3.14, 3.16, 3.18 and 3.20

**Comment by cicindel** [comment]
My Ubuntu Gnome 16.04 (3.18) also often freezed after suspend - it allowed me to type a password but then hung (if I just lock the screen it's fine). I read this thread and noticed that wifi is trying to connect when it hangs.I disabled the extension (installed from extensions.gnome.org) and after four days of suspending my laptop, no hang. I'll try the workaround with switching wifi off during login (I have a hardware switch) as I like this extension, but given that I'd have to remember the switch everytime or else I'm risking loosing my session, and given that too often I'm waking up my notebook in hurry, trying to find something quickly, maybe I'll just have to live without it.

**Comment by cicindel** [comment]
After recent update seems to be fixed *knocking on the wood*..
