### ISSUE TITLE
Breezy weather shows shows stormy icon

### ISSUE THREAD

**Issue by adamclaassen** [jenslody/gnome-shell-extension-openweather#83]
Weather data pulled from forecast.io with conditions "breezy" results in a stormy weather icon being displayed, in the top bar and the drop down menu. The icon pack I am using does not have any icon named `weather-breezy-symbolic`, but symlinking another one to that file name does not fix the issue.

**Comment by jenslody** [comment]
Forecast.io provides a list of possible icons in their api, their should be nothing for breezy.
They just have "clear-day", "clear-night", "rain", "snow", "sleet", "wind", "fog", "cloudy", "partly-cloudy-day" or "partly-cloudy-night".
If anything else appears, I sjow it as "weather-sever-alert".

**Comment by adamclaassen** [comment]
I see in the file `src/forecast_io.js` that you've actually coded this wind->stormy behavior in, which makes sense, given that none of the default icon sets (or 3rd party ones, it appears) have a dedicated wind icon. I'll close the bug, as this is intentional behavior. 

That being said, I think the stormy icon is a bit misleading for what the conditions actually are during that forecast, but there isn't really a solution to this problem without icon pack support.
