### ISSUE TITLE
Open Weather Map API key

### ISSUE THREAD

**Issue by burdges** [jenslody/gnome-shell-extension-openweather#84]
I'd recommend installing a default API key for openweathermap.org because users obtaining their own creates a unique identifier than can be used to track them.  

We should ideally use the same API key as a common application so as to better anonymize users.  Is one of these a good candidate?  http://openweathermap.org/examples  I'd wager they do not mind applications using a fixed API key, but if they do, then they might still ignore GNOME Shell users. 

We could alternatively build a script to obtain a new API key every so often, but that's probably less anonymous than giving everyone the same API key, especially the same API key as a common application.

**Comment by jenslody** [comment]
I already asked openweathermap for an api-key, that can be used for FOSS applications with less restrictions.
They already answered, but also said, that it will take some days.
If the key is still a personal-key, that can not be supplied, I will set up a proxy on my own server, that hides the key from the end-user.
Then the user can chose between using openweathermap directly (with an own key) or via my server (with my key).

**Comment by zagortenay333** [comment]
Did they post anywhere on their site about this FOSS-whitelist? I can't find it anywhere. I'd need this key for my conkies as well.

**Comment by jenslody** [comment]
They describe the procedure to require a FOSS key in the FAQ: https://openweathermap.org/faq#error401 .

**Comment by zagortenay333** [comment]
Ah thx!
