### ISSUE TITLE
Center upcoming forecasting

### ISSUE THREAD

**Issue by alxxlc** [jenslody/gnome-shell-extension-openweather#90]
I don't know if this is something everyone will want but it would make this extension a little more appealing to the eye. When there are only a few upcoming days being displayed, there is a gap between the last day being displayed and the window border. It might look a little better if the days are spaced out so everything is centered in the space they are provided and have equal spacing between the side margins and spaces between each day. If this wouldn't be something that is a default, it would be nice to have an option for this in the settings.

I'm including a screenshot of what I'm talking about just to be clear about this issue.

How it looks now:
![weatherscreen](https://cloud.githubusercontent.com/assets/1102632/10825348/a23b5742-7e32-11e5-9fe1-9018a91aaedf.png)

How I think it could look better:
![weathercentered](https://cloud.githubusercontent.com/assets/1102632/10825636/ec31bd4a-7e33-11e5-87a6-96ce46d98310.png)

**Comment by stefannagy** [comment]
Have a look at the 'Layout'-tab in settings, there should be a 'Center forecast'-option. There's no equal spacing between the side margins and spaces between each day… But have a look at it – at least I like it as it is now.

**Comment by alxxlc** [comment]
Wow. I never hit that arrow to get over to the other tabs. I can't believe I missed that.

**Comment by jenslody** [comment]
No problem.
