### ISSUE TITLE
Colour of day in dropdown is illegible against background

### ISSUE THREAD

**Issue by jamespo** [jenslody/gnome-shell-extension-openweather#94]
Using this excellent extension in Apricity (Gnome 3 based Arch derivative) the colour of the day is very close to the background applet colour.
![weather](https://cloud.githubusercontent.com/assets/1472544/11161213/722a68ac-8a6e-11e5-9de1-48e0b55f9b94.png)

**Comment by jenslody** [comment]
Which theme do you use, and which version of the extension ?

**Comment by jenslody** [comment]
It now works for me in uptodate apricity with default theme ("Arctic apricity") after removing and reinstalling the extension.

**Comment by jamespo** [comment]
works for me too, fantastic work!
