### ISSUE TITLE
Unable to chose location

### ISSUE THREAD

**Issue by Kuro-Maii** [jenslody/gnome-shell-extension-openweather#97]
To day I installed this via [gnome extentions](https://extensions.gnome.org/extension/750/openweather/) when I wanted to add my location I found my self unable to.
Here is what I did and what ( didn't ) happen:
* clicked the plus button on the preferences page
* entered my city name
* (nothing happened)
* clicked [find]
* (nothing happened)
* clicked [save]
* (nothing happened)
* looked up my gps coordinates and filled them in ##.######N, ##.######E
* clicked [find]/[save]
* (nothing happened)
* altered GPS to ##.######, ##.######
* clicked [find]/[save]
* (nothing happened)
* tried different orders of both "[city], [country code]" and "[longitude],[latitude]" with and without compass letters ( N/S,E/W )
* clicked [find]/[save]
* (nothing happened)
* clicked [cancel]
* ( the window closes as expected, and nothing changed as expected )

**Comment by jenslody** [comment]
* which distro do you use ?
* which version of gnome-shell ?
* which version of the extension (preferences -> about-tab) ?
* which geo-location provider ?

**Comment by Kuro-Maii** [comment]
* distro: ubuntu-gnome 14.04.3
* gnome-shell --version -> GNOME Shell 3.10.4

when I click the the extension, then the "wrench and screwdriver" icon in the lower right there are no tabs [screen shot](http://i.imgur.com/d3MlEVd.png) ( I removed my api-key for open weather map for obvious reasons when I took the screen shot )
is there a different way to find the version of the extension?

I looked in the metadata.json file, according to that I am using:
"version": 36

I do not remember which geo-location provider that I used when I looked that up for a different tool that I use to get accurate sun up/down and twilight times.
I have them aliased in that command and are correct according to google maps.
If I use the "geo coords" from openweathermap I get the same flow as described above.

**Comment by Kuro-Maii** [comment]
hmmm...
I did not try to use the literal format that is on openweathermap.org which is `[ #.##, ##.## ]`
when I entered it like this the save button worked but the forecast values did not match up.
when I swapped both values around ( to look like `[ ##.##, #.## ]` ) the forecast values where correct.

this tells me that it is not clear how we need to enter the geo coords.
to help with this problem I would like to suggest to give an error/message when the save/find and the values are not in a working format.

also please note that the find button still did not do any thing when I used the the format I just discribed

**Comment by jenslody** [comment]
Version 36 uses openmapquests nominatim, but they changed their api and force the use of a key now.
Unfortunately the rest of the newwer extensions is not compatible to 3.10 any more.

Can you try to replace
```javascript
const OPENWEATHER_URL_BASE = 'https://open.mapquestapi.com/nominatim/v1/'; 
const OPENWEATHER_URL_FIND = OPENWEATHER_URL_BASE + 'search.php';
```
with
```javascript
//const OPENWEATHER_URL_BASE = 'https://open.mapquestapi.com/nominatim/v1/'; 
//const OPENWEATHER_URL_FIND = OPENWEATHER_URL_BASE + 'search.php';
const OPENWEATHER_URL_BASE = 'https://nominatim.openstreetmap.org/'; 
const OPENWEATHER_URL_FIND = OPENWEATHER_URL_BASE + 'search';
```
in prefs.js and restart the shell.

And of course give feedback if it works.
If it works I can probably prepare a new version of the extension for 3.10 only.

**Comment by pbielefeldt** [comment]
I have a probably similar behaviour on CentOS 7 (Gnome shell 3.8.4): I *can* enter a city's name, and it *is* detected and linked to the ID - but I cannot hit "OK" to finish the action. That's all in the "add a city" submenu.  
See: https://lut.im/THcrQcFZQx/zFDGLaWMGY7sieTa.png

I both occurred with an install from extensions.gnome.org and a "fresh" git pull, install,...

**Comment by Kuro-Maii** [comment]
@jenslody 
the solution works. 

as added feed back:
the search for my city comes back with a
{city name, government region name, province ( state? ) name, country [N/S, E/W]}
pattern.
It is a bit much and I do not know how it will be for other regions.
If it is the same pattern for more ( all? ) regions the government part and possibly the state part can be trimmed out.

It not something that is a breaking thing and more like a personal style if anything and can be edited in to the amount of info one wants.

So all in all I would say: ship it. ^.^

**Comment by jenslody** [comment]
@Kuro-Maii :
I just uploaded a version, that should work with 3.10 again for review on extensions.gnome.org.
It's the actual trunk and might have a cosmetical issue with the spinner, shown while searching a location, but this should not be a reall problem.
At least it works on my old Fedora 20 vm with 3.10.
I did not (yet) test it on older Ubuntu/Debian.

**Comment by jenslody** [comment]
I also readded support for gnome-shell 3.8 and uploaded the new version for review.

**Comment by Kuro-Maii** [comment]
thanks,
it now works like a charm on 14.04 ubuntu-gnome
